[package]
name = "mw-agent"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "agent"

[dependencies]
mw-binding = { path = "../binding" }
mw-okf = { path = "../okf" }
serde.workspace = true

[dev-dependencies]
mw-binding = { path = "../binding" }
mw-okf = { path = "../okf" }
